#!/bin/bash

if [ "$1" = "--help" ]; then
  echo "Uso:"
  echo "--path <caminho do gsan_cadastro>"
  echo "--files <lista de arquivos a serem testados>"
  echo "--log-clear <limpa todos os logs das aplicações>"
  exit
fi

PATH_ONLINE=$(pwd)
PATH_CADASTRO="../gsan-api"
LOG_CLEAR=0

while test "$1"
do
  if [ "$1" = "--path" ]; then
    shift
    [ -n "$1" ] && [ -d "$1" ] && PATH_CADASTRO=$1
  fi

  if [ "$1" = "--files" ]; then
    shift
    FILES=$@
  fi

  if [ "$1" = "--log-clear" ]; then
    LOG_CLEAR=1
  fi

  shift
done

cd $PATH_CADASTRO
PID_FILE="$(pwd)/tmp/pids/test.pid"
[ "$LOG_CLEAR" == 1 ] && bundle exec rake log:clear

RAILS_ENV=test bundle exec rake db:seed
RAILS_ENV=test bundle exec rails s -p 3002 -d -P $PID_FILE

cd $PATH_ONLINE
[ "$LOG_CLEAR" == 1 ] && bundle exec rake log:clear

if [ -n "$FILES" ]; then
  bundle exec rspec $FILES
else
  bundle exec rspec spec
fi

if [ -e "$PID_FILE" ]; then
  PID=$(cat "$PID_FILE")
  kill -9 $PID && rm "$PID_FILE"
fi
